# Generated by Django 6.0.3 on 2026-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude'), ('gemini', 'Gemini')], db_index=True, default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.CharField(db_index=True, default='demo-user', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], db_index=True, default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_id', 'updated_at'], name='Chat_conver_user_id_b7d7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['provider', 'updated_at'], name='Chat_conver_provide_c80f37_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='Chat_messag_convers_f93d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'role'], name='Chat_messag_convers_458f7e_idx'),
        ),
    ]
